sys1=tf([1],[1 1/32])
figure(1)
step(sys1)
title('step response of transfer function = 1/(s+ 1/32)')
figure(2)
impulse(sys1)
title('impulse response of transfer function = 1/(s+ 1/32)')

sys2=tf([1],[1 32])
figure(3)
step(sys2)
title('step response of transfer function = 1/(s+32)')
figure(4)
impulse(sys2)
title('impulse response of transfer function = 1/(s+32)')


sys3=tf([1],[1 160])
figure(5)
step(sys3)
title('step response of transfer function = 1/(s+160)')
figure(6)
impulse(sys3)
title('impulse response of transfer function = 1/(s+160)')
